<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Blaze Privacy Policy</title>
</head>
<body>
  <h1>Blaze Privacy Policy</h1>

  <p>This GPT does not collect or store personal information. Blaze runs on OpenAI's platform and follows OpenAI’s data policy.</p>

  <p>All responses are generated by AI and should not be taken as professional advice.</p>

  <p>For questions, email us at: <strong>Jeng1ry81@icloud.com</strong></p>
</body>
</html>
